Occupy Seattle General Assembly, 2012-01-10

Minutes taken by David Lindes.

* Orientation

Wording notes are not on hand, so improvised.

For future reference, they're at
http://occupyseattle.org/document/general-assembly

* Introductions of new people

- Bang -- new to being on time
- Jackie -- is new.

* Workers Reports

[This is a new section, for people who work, or used to, reporting
about that.]

- One report about a firing, suspected of being gender-based.
  Suggestion to reach out to the Seattle Solidarity Group.

- Someone from Mental Health and Chemical Abuse Division... (sorry,
  details missed.)

* Work Group Reports

** Court Solidarity, Duff

Friday, January 13th.  1:30pm. Seattle Municipal Court, Room number 1103.

One of our Brothers, Ed Mast, has a court date, stemming from his
arrest on October 5th.  You may remember October 5th.  It was the
first police raid on our camp at Westlake.  The police raided us with
violence and horses.  32 of us were arrested.  Ed's date is 1:30 this
Friday.  Courtroom 1103.  He does not have any more information about
his co-arrestees from October 5th.  Some of them may have been
arrested and never charged, in the classic cop technique of crowd
control by arresting with no intent of charges.  However if any of you
have other information about other October 5th arrestees, please
contact Duff.

October 5th was a significant day.  It showed what Chief Diaz and
Mayor Mike McGinn think of the Occupy Movement.  We were one of the
very first occupations to have been violently raided.  We need to come
out en masse on Friday.

** John, Civil Disobedience Workgroup

First meeting will be on Monday, here, 6pm.  Everybody come.

** Community over Capital working group

It is a continuation of the revolutionary spirit of the 10th and Union
warehouse occupation.  They are working on still reclaiming that
warehouse, and addressing the multi-family tax exemption program,
which is an extremely corrupt city program, and discussing how to
organize our physical landscape, so that we are more connected to each
other.  All the information is online.

First meeting is Sunday, at 5pm, here.

** Rise and De-colonize

Working with the United Farmworkers on two dates:

*** National Day of Latina Activists, January 20th

*** January 28th, Days of Action, down the coast, against Dairigold

Against the farmers that abuse their workers, in almost 3rd-world
conditions.  Flyer is coming.

This is an escalation to a national day of May Day general strike.

** Gender Equality Caucus

Meeting this Sunday, 11am, at Bauhaus

They've started planning an all-day teach-in.  They're currently
researching topics and speakers.  Topics so far include:

- The Gender Binary (linking with Culture Jamming)
- Reproductive Oppression
- Human Trafficking and Anti-Slavery
- and more!

If you have suggestions and can't come, please let Kristin know about
speakers.

* Action Announcements

** Guantanimo Protest

from Greg Spense Wolf

Tomorrow, at the Jackson Federal Building, 2nd Avenue, Marion and
Madison:

Silent Vigil, 5-6pm.  Protesting Guantanimo prisoners and indefinite
intention.  Organized by Amnesty International, Code Pink, and ...

At 6pm, Occupy is marching to Obama's headquarters, and reading
Guantanimo stories in Jumpsuits.

** MLK Speech

Thursday, day after tomorrow, at 3rd and University, where Garden of
Rememberence is, they're going to be listening to a Martin Luther King
speech, "Where do we go from here?" from 1967.  It's a great speech.
And unfortunately the MLK event inside, which is one of the King
County events, cannot play any of the speeches, because the company
who owns the right to the speeches, charges a lot of money.  So
they've organized this event outside the building, where the recording
will be played, and anyone who'd like to listen, please come and join
the crowd.

11:30-1pm, 3rd and University.  Thursday, 2012-01-12.

** Bring Diaz Down

Campaign is having a march, this coming Saturday, 2012-01-14.  It's
going to be in part a speak-out about police brutality.  And the other
half will be a torch-light march.  They're awesome.

It's going to start at 23rd and Union, at 4pm, on Saturday.  Then
they'll march to the East Precinct in Capitol Hill.  There they'll
have another speak-out.

The torches only last 20 minutes, so they will light them as they're
cresting the hill, about Madison and Pike, and come down in force,
with them all lit.

If you come, please be aware, the flames get really big.  So please
provide enough space between you and the next person.

This is in support of the call for the resignation of Seattle Police
chief John Diaz.

* Pre-proposals

Announcements of proposals to be voted on at a future GA.

None heard.

* Discussion

Call for topics for discussion in a small group:

- New Blood for Facilitation Group
- A visit to 9 occupies all up and down the coast; discussing
  coordination options, etc.
- Accountability General Assembly, which was a pre-proposal last week,
  to devote one of the discussion GAs to talking about Accountability
  and mutual support.

-----
breaking at 2012-01-10, 19:42
-----

** Sharing from discussions

In the group that you were in, was there:

- something that made your heart sing
- something disgusting
- something inspiring
- ... ?

*** Accountability GA group

Only two people, and they'd really like more input.

Transformative Justice, which is an alternative model to the existing
justice system, to address conflict in a way that's in line with our
current values.  Community-based accountability, rather than a
punitive system of justice.

*** random stuff...

He was in the military for a long time, and under the impression that
the united states was this giant protector of peoples' rights.  He
spent a lot of time away from his family; spent a lot of time on the
seas.  Now this NDAA act, and the authorization to use military force,
and the Patriot Act has been expanded, and it violates our basic
rights, that so many millions of Americans have died in these wars,
promoting these rights.  He doesn't want to sit around and let it be
taken away.  It pisses him off.

The other issue was foreclosures on all the homeless people.  That's
why on Thursday, they're having a march on Occidental, WaMu theatre
area, it's on the calendar.  The banks are pulling a fast one, trying
to get people to bring their deeds in, and modify their loans.  They
can't even tell people where their check is going -- if any money at
all is even going to the account number that's on the check.

*** New blood for facilitation

It seems like such a dry area, and it is somewhat dry, however, it's a
great opportunity for more of us to get involved in the meetings, and
show greater variety.

What she wants to do as a new helper for facilitation is to invite
people to facility with her, particularly other women, people who are
not white, people of color.  It would be awkward for her to approach
people she doesn't know to ask them to facilitate, and it may be
awkward to be approached by someone you don't know.  Let's have more
of us doing it, and take turns.

Direct response: It will also make more capacity for facilitation if
like workgroups take on facilitation for GAs.  Some groups have talked
about doing this.  This might be a way to allow more people building
the skills, and bringing the content of their workgroup to the broader
community.

Further response: The reason that some facilitators are stepping back
is to make a space for this to happen.  This movement is not
"leaderless", it's "leaderfull" -- here's an opportunity for training
of leadership.

*** Open Question:

Because we constantly have, and keep having, debates about
non-violence versus diversity of tactics -- which effects people
differently based on their life experiences and background:

Will the positive of having someone in facilitation outweigh the
negative of having facilitators not have a voice in the GA?

*** Semantics

An opinion that we should be leaderless, rather than leaderfull.
People come off as a leader, so they end up being a leader by default,
they get seen as a leader...

*** follow-up on facilitation

He hates facilitating, he's done it a couple times, this is the first
time he's come to a discussion GA.  He doesn't like to
facilitate... and can understand why someone who wasn't sure that
their point of view would be heard as a facilitator.

Maybe we could amend the current system so that facilitators do have
a way to get on stack, so we don't have to have a binary thing of
facilitating versus having the ability to get on stack.

*** meta point:

If that question is a real question, it shows how under-represented
certain populations are here.

*** how we feel about it

It's not only that people of color are under-represented, it's how we
think about it.  The fact that we're saying this is part of the
problem.

She hates the idea of anybody's voice being silenced.  She'd like for
everybody to have a chance to have something to say.

*** Change facilitators mid-GA?

One suggestion for a way to maybe have it not be locked.

*** more discussion...

- having a process group was originally not about facilitating, but
  about training people to facilitate, and having others do that.
- That doesn't seem to be the current role of the group, and there's
  the thought that it was a pretty solid idea.
- We as an assembly should probably be more pro-active at volunteering
  to facilitate, and the group should be more active in trying to
  recruit people.  Something that everyone needs to just collectively
  work on.
- Idea that we always have at least two facilitators, and so that one
  of them can always raise their hand, and the other facilitator will
  run the process and get them on stack (even if only at the end)
- The job of facilitation is to move the process along, but the more
  people that you have doing that, the easier it is to have people
  coming to it easily.
- The point about taking someone's voice away -- completely
  understood.  But if everyone has to have a point in time when you
  have to check your voice and *don't* get to say something...  Maybe
  that's a useful thing. If more people are open to it and training
  for it, then this will get shared.  We're doing a disservice to some
  of our fellow occupiers by having the same people facilitating every
  night.
- people shouldn't have to choose.  Maybe having more facilitators
  would allow a way for facilitators step up and be speaking.
- There are many people on the team, and people doing agenda,
  time keeper, etc., can speak.  Only two people under the current
  rules can't speak.  But if we amend things so that they can take
  turns, then nobody's voice is unheard.
- One potential problem with the current system is that if you're fine
  with not saying anything one night, but then something comes up in
  the meeting that is highly relevant, then you might want to speak,
  when you'd been fine with facilitating and not speaking previously.
- doesn't always come, wouldn't want to facilitate on the few days
  they do come, because they specifically want to participate in
  something that day.
- so just come more often.  :)
- The point about checking your ego the night you facilitate: there's
  a positive there -- you trust the group enough that even on an issue
  that you care a lot about, that there would be someone there who
  would represent your desires, your philosophy, your interest, in
  balance, ideally, with the multitude of other interests.
- can't honestly see any reason why the facilitators shouldn't be able
  to speak.
- If you're a person who is marginalized, you can't necessarily trust
  that someone will voice what you want to bring up.
- One purpose for keeping people from speaking is to minimize bias in
  who gets to speak.
- there's also a need to recognize that there is an issue of
  capacity.  We have high expectations on the level of commitment for
  most people.  8 GAs a week is a really high level of participation
  -- even those who are highly committed, that's just really hard.
  Perhaps too we need to re-consider the number of meetings that we
  have every week.
- Response to "trusting the assembly"...  This is one of the few times
  he's been able to say this: He looks around the room and doesn't see
  anyone who he strongly distrusts, but usually there are... there are
  people within the group who he really distrusts and doesn't want to
  have them be representing him.  Or even for the people that he does
  trust to truly represent him.  Everyone has unique experiences;
  everyone has a unique role within this movement; etc.  If we're
  talking about something, say, that has to do with police, and one
  person has a different perspective because they just got pepper
  sprayed, or has other history, or whatever, it would be unfortunate
  not just for that person, but for all of us.  There's something to
  be said for trusting people, but he doesn't think trust should ever
  mean that you're giving up your voice.
- lately, he's not been called on, but the things he's wanted to say
  have gotten said by others.  Earlier in Occupy, though, he had lots
  of things where he was the only one who was saying things that he
  felt were important to get said.





* Announcements

** 23rd and Alder: Still there.

** UW's first GA

different from OS's GA, and within 30 minutes, got kicked out by
campus police.  Some (OS members) wanted to sit down and stay there,
but all the students just kind of picked up and went.

Bigger focus on small discussion groups, and just throwing things out
at the same time, when they came back together.

Did get some notes and contacts.  Also planning to start GAs at
Seattle University.

** Moving...

Down-sizing; stuff is available... kitchen stuff, etc.... misc stuff.

* Song

We shall overcome.
-----
