Intergroup meeting notes, 2012-01-10:

* Attendees

- Norm, Occupy Chaplains
- Sonia, Supply & Storage (had to leave early, so only here for part
  of the meeting)
- David L. (note taker), Media
- Aliana, Media
- Duff, Environmental Justice
- Bang, Food Not Bombs & Food Group
- Stian, ICT
- Mike, Medical
- Kristin, Gender Equality Caucus & Bring Diaz Down
- Carol, Process and Facilitation

* Agenda

- Budget approvals
- Group status
- Proposals and announcements

* Budget

Very little detail on there, merely the following:

** budget proposals

quoted verbatim from:
http://occupyseattle.org/resource/weekly-budget-proposals

#+BEGIN_EXAMPLE
The following workgroup budgets were proposed at the 1/9/12 intergroup meeting --

Food Not Bombs - $130
Outreach - $50
Morale - $200
City Hall - $120
#+END_EXAMPLE

** What to do?

We don't currently have anyone from Finance here, so we don't know our
balance or anything.

There's a belief that if the budget made it online, then that means it
was approved at the prior day's meeting.

** Food Not Bombs - $130

since we have a representative here, getting details from that.

Budget has been decreasing at a purported 20% per week

- $60 on gas, to transport receipts of free vegetables that we collect
from around town.
- $10 per day for each kitchen that cooked.  Thus $70.

Proposal to approve the Food Not Bombs budget.

Budget approved without opposition.

** Outreach - $50

Presumed to be for miscellaneous expenses.

Proposal to approve this.  Seconded.

Budget approved without opposition.

** Morale - $200

Originally requested for $400, and Intergroup asked that they break it
up into $200 allotments.  These are for "Benefit" events, and would be
expected to be re-paid.

Proposal to approve this.  Seconded.

Budget approved without opposition.

** City Hall - $120

We've been told that they have already had their request satisfied,
because Engineering canceled their budget and gave $180 to City
Hall, and they're required to have a receipt by Friday.

No action taken.

** Summary

$380 approved.

* Group status
** Food not bombs

Have been moving towards a 4-day, scaled-down menu.  Now up to 7 days
a week, for GAs, action days, etc.  They need to re-assess things...
They request to cut things back down to 4 days of GA.

They're going to stay on the schedule until it costs them more.
They're just expressing a financial concern, and that they will most
likely scale back to the previous schedule.  Will most likely stay at
the $130 weekly budget.

** Environmental Justice

Would like to invite everyone to an event:

Protest event against the Seattle Steam Incinerator (to try to shut it down)

Starting at noon, Saturday, February 11th, 2012 (2012-02-11), at
Westlake Park.

Then marching to Victor Steinbrook, bringing tents, with intention to
occupy over night with round-the-clock teach-ins, "die-ins", and
smaller direct actions within the broader action.

They anticipate requesting $100, mainly for flyers.  They've got a
good discount on flyers from Golem Printing.


Question: Is there any access to electricity -- perhaps battery or
pedal-powered options or something for running a computer and
projector.

Supply and Storage is referenced as having Marine Batteries, and other
resources will be given off-line.

** ICT

ICT will be meeting on Friday, to talk about a website re-design.
2012-01-13, 6:00pm.

They request that any ideas for what should be included in the
re-design, or considered in it, be e-mailed to ICT before hand, so
they can consider them in advance of and at their meeting.

occupyseattleict@gmail.com

Also, just a request that people remember to use the intergroup
mailing list, especially for minutes and such.

Details, archives, subscription, etc. at:

http://lists.occupyseattle.org/cgi-bin/mailman/listinfo/intergroup

** Media

Media will be covering the following marches this month:

- John Diaz, January 14th
- Martin Luther King, Jr. Day, January 16th
- Occupy The Courts / Citizens Ignited against Citizens United,
  January 20th and 21st.  This will be covered with a reporting team,
  similar to what might be expected from a TV media outlet.

If there are other events that need covering, please contact media
via e-mail to: occupyseattle.media@gmail.com

** Gender Equality Caucus

*** Teach-in:

They're having an all-day teach in, Sunday, January 22nd (2012-01-22).

Location and exact time is TBD.

Topics to include at least:

- Reproductive Oppression
- Human Trafficking, anti-slavery
- Gender Binary (including Culture Jamming -- how we've been trained
  to think in the Gender Binary)

People can come for one or all of these topics.

*** Content

There's a request from ICT for content -- writings, or whatever --
that they can post on the Occupy Seattle Facebook page.

ICT is referred to check on:

http://www.facebook.com/occupyseattlegenderequality

And GEC will send to occupyseattleict@gmail.com

** Bring Diaz Down

*** March for Bring Diaz Down

Starting 4pm, 23rd and Union, this Saturday, 2012-01-14.

They've made some torches, which will burn for about 20 minutes.

Medical is preparing to treat any burns for this.


*** Contact for the ACLU?

Wondering if there's a contact for the ACLU?  Their contact fell
through.

** Process and Facilitation

There's going to be a large push to have new people do the work,
because they don't have enough people.

One volunteer spoke up.  They'd still like more.  Lots more.

** Medical

They will have street medics at the Bring Diaz Down march, and also
the People Ignited Against Citizens United event.

Also, making a call that if anyone has any direct actions that they're
planning, that they would like medics to be at, please e-mail:
occupyseattlestreetmedics@gmail.com.

Unsure about their presence at the MLK march.

Request for them to put the February 11th Environmental Justice event
on their calendar.

* Proposals and announcements

** Rise and De-colonize

*** National Latino Activists Day

This month, Rise and De-colonize, Hip Hop Occupy, will be having an
event, the 19th and 20th, for National Latino Activists Day.

*** United Farm Workers action against Dairigold

About inhumane labor conditions.

Saturday, 2012-01-28.  Rise and De-colonize may assist with this event.

*** Requests for money

They will likely also be requesting money for this.

-----
Meeting adjourned, 2012-01-10, 18:41.
-----
