Notes for an OSMedia TV show...

Held 2011-12-22, at [[http://www.uptownespresso.net/locations/#location-belltown][Uptown Espresso, Belltown]].  Starting at 2:45 (2:30 officially).

* Attendees
- Brett H
- David Lindes

* Finding a host

** TODO we need a host...

*** Rex?

Brett knows a guy named Rex that he thinks would be good...  Rex
doesn't know about this yet.

** What functions are we trying to provide?

- Provide anther perspective (to balance popular media -- stuff you
  hear at the GAs, but don't see in the popular media)... what is the
  media missing?  How can we take the media clips and undermine them
  with our own content?
- keep as a mantra: Admit our mistakes, and try to learn from them.

[note: enter brainstorm.]

- don't keep coercion going.
- humor raises awareness, encourages viewership
- serious treatment provides depth
- two different shows?
- two voices in the same show?
- provide at least a separate narative than mainstream media and the
  police (and the stranger)
- provide a narative *from the occupy movement*...
- show what a GA is really about -- love, etc.  clunky, but good.
- gather support for the movement -- gather people....  slowly create
  a voice for the movement.
- "I would be for this, probably, but I don't understand what it's all
  about" -- try to give people like this an answer.
- if you go to a Greatful Dead concert, what is it about?  You'll get
  lots of different answers.  Why would you expect a big mass of
  people to have one united voice?  Yet the media is always pushing
  the movement to have a cohesive voice, because it's easier to report
  on, easier to attack, etc.
- if you could create a media where there is a way to show the voices,
  perhaps a cohesive voice could slowly emerge.
- most of the folks in this movement would probably agree with getting
  the money out of politics, for example.
- "we vow to end the monied corruption of our democracy" -- from
  [[http://www.adbusters.org/campaigns/occupywallstreet][adbusters]].


** What do we want in a host?

It depends on what we want to go for, but... some ideas:

- 

** Foundation

What things do or do we not want to try to emulate?

- Daily Show?  Maybe too frequent, and too contemporary?  And maybe we
  can't be that frequent, and thus need to step back a little?  Dust
  settles on things, and so a knee-jerk reaction may stop making
  sense.


* How to approach it?

** 5-minute pilot?

Perhaps we can start this out by shooting a 5-minute pilot...

** Re-cap?

maybe a re-cap, end-of-the-year, stage 2 occupy...  3 or 4 episode
re-cap.

* Next steps?

** Talk to two or three more people...

from OSMedia, and/or the Occupy movement in general, and see what they
think is lacking

dual-purpose thing: interview folks about what they want, and make
that a video, that gets put up.

** TODO Tuesday, go to GA -- interview folks afterwards.

make an announcement during GA:

What would you like to see out of a new
show/podcast/documentary/whatever about the Occupy Seattle movement?
Several of us are thinking about producing something, and we're
looking for two things:

(1) Collaborators;
(2) Opinions about what everyone here would like to see in such
content.


* out of band idea:

meme stamps -- have little blurbs defining a meme, and have a graphic
design for a stamp for that meme... stamp over things that are being
said that are in line with, or opposed to, or whatever, the meme.
Example stamps:

- impossible hamster
- any other obsurdity of thought
